apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-homelab-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/oquaglio/k3s-homelab.git
    targetRevision: HEAD
    path: argocd/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: false  # Don't auto-heal staging - allow manual testing
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
