apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: c64-emulator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/oquaglio/k3s-homelab.git
    targetRevision: HEAD
    path: charts/c64-emulator
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
